spring.application.name=displine

#Troque Discipline caso tenha criado o Database com outro nome
spring.datasource.url=jdbc:postgresql://localhost:5432/Discipline

#Coloque seu usuario do postgres aqui:
spring.datasource.username=postgres

#Coloque sua senha do Postgress aqui:
spring.datasource.password=1877


spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true